# Conversion functions

#' Convert Excel-style Numeric Dates to Date Class
#'
#' Converts numeric date representations (often imported from Excel files with text column types)
#' back into native Date objects using the standard Excel Windows baseline origin.
#'
#' @param date_vec A numeric vector representing fractional or whole days since the origin.
#' @return A `Date` vector.
#' @noRd
convert_numeric_date <- function(date_vec) {
  cli::cli_progress_step("Converting numeric {.var Date} column to {.cls date}")
  lubridate::as_date(floor(date_vec), origin = "1899-12-30")
}

#' Convert Excel-style Numeric Times to Character Strings
#'
#' Converts numeric fractional-day time values (frequently generated by Excel text formats)
#' into standardized historical character time strings.
#'
#' @param time_vec A numeric vector representing fractions of a 24-hour day (0 to 1).
#' @return A character vector formatted as "HH:MM:SS".
#' @noRd
convert_numeric_time <- function(time_vec) {
  cli::cli_progress_step(
    "Converting numeric {.var Time} column to {.cls character} in {.val %H:%M:%S} format"
  )
  format(hms::as_hms(time_vec * 60 * 60 * 24), "%H:%M:%S")
}

#' Combine Distant Date and Time Vectors into a Datetime Object
#'
#' Merges independent date and character time vectors into a single robust date-time
#' structure, seamlessly propagating missing (`NA`) values across both inputs.
#'
#' @param date_vec A vector of `Date` objects.
#' @param time_vec A character vector representing time of day (e.g., "HH:MM:SS").
#' @return A `POSIXct` datetime vector in UTC.
#' @noRd
combine_datetime <- function(date_vec, time_vec) {
  cli::cli_progress_step(
    "Creating {.var Datetime} column from {.var Date} and {.var Time} columns"
  )
  datetime_vec <- ifelse(
    is.na(date_vec) | is.na(time_vec),
    NA_character_,
    paste(date_vec, time_vec)
  )

  lubridate::ymd_hms(datetime_vec)
}

#' Standardize Pipeline Datetime Vectors to Pacific Local Time
#'
#' Enforces a specific source timezone onto a data vector before shifting and standardizing
#' the final output to Pacific Local Time (`America/Los_Angeles`). Includes defensive validations
#' against missing or invalid Olson timezone strings.
#'
#' @param datetime_vec A `POSIXct` datetime vector.
#' @param tz Character string representing the source timezone (e.g., "Etc/GMT+8").
#' @param config_path Character string path to the survey's YAML configuration file used for
#'   contextual error reporting.
#' @return A `POSIXct` datetime vector adjusted to `America/Los_Angeles` time.
#' @noRd
standardize_timezone <- function(datetime_vec, tz, config_path) {
  cli::cli_progress_step(
    "Standardizing timezone of {.var Datetime} column to local time ({.val America/Los_Angeles})"
  )

  # Exit with error if no timezone is specified
  if (is.null(tz) || tz == "") {
    cli::cli_abort(c(
      "x" = "No {.field timezone} specified",
      "i" = "A valid {.field timezone} parameter must be provided for an input when processing date-time fields",
      "!" = "Please specify a valid Olson timezone string (e.g., {.val Etc/GMT+8}, {.val America/Los_Angeles}) in {.path {config_path}}"
    ))
  }

  # Ensure the string provided is an actual recognized timezone name
  if (!tz %in% OlsonNames()) {
    cli::cli_abort(c(
      "x" = "Unknown {.field timezone} string {.val {tz}} provided for input in {.path {config_path}}",
      "!" = "The value must match a valid system name found in {.fn OlsonNames}."
    ))
  }

  # Force timezone for datetime_vec from UTC to the one specified in configuration file
  datetime_force <- lubridate::force_tz(datetime_vec, tzone = tz)

  # Standardize timezone to local time (America/Los_Angeles)
  lubridate::with_tz(datetime_force, tzone = "America/Los_Angeles")
}

#' Standardize Depth Parameters to Meters
#'
#' Validates and scales survey water depth records to standard metric units (meters).
#' Automatically skips operations if values are already declared in meters.
#'
#' @param vec A numeric vector of depth measurements.
#' @param depth_unit Character string representing the units of the `Depth` parameter. Supported
#'   options: "meters", "feet".
#' @param config_path Character string path to the survey's YAML configuration file used for
#'   contextual error reporting.
#' @return A numeric vector representing depth scaled to meters.
#' @noRd
convert_depth <- function(vec, depth_unit, config_path) {
  # Set up progress message
  status <- new.env()
  status$msg <- ""
  step_id <- cli::cli_progress_step(
    msg = "Standardizing units of {.var Depth} column",
    msg_done = "Standardizing units of {.var Depth} column{status$msg}"
  )

  # Define valid units for depth_unit
  valid_units <- c("meters", "feet")

  # Exit with error if col_units isn't specified
  if (is.null(depth_unit) || depth_unit == "") {
    cli::cli_abort(c(
      "x" = "No {.field col_units} provided for {.var Depth}",
      "!" = "Please specify a valid {.field col_units} in {.path {config_path}}",
      "i" = "Supported units are: {.val {valid_units}}"
    ))
  }

  # Check for standardized depth_unit and provide error if no match
  if (!depth_unit %in% valid_units) {
    cli::cli_abort(c(
      "x" = "Invalid {.field col_units} {.val {depth_unit}} for {.var Depth}",
      "!" = "Please specify a valid {.field col_units} in {.path {config_path}}",
      "i" = "Supported units are: {.val {valid_units}}"
    ))
  }

  # Skip if depth_unit is meters
  if (depth_unit == "meters") {
    status$msg <- cli::format_inline(
      "... already in {.val meters}. No conversion necessary."
    )
    cli::cli_progress_done(id = step_id)
    return(vec)
    # Otherwise, if depth_unit is feet, convert to meters
  } else if (depth_unit == "feet") {
    status$msg <- cli::format_inline(
      "... converted from {.val feet} to {.val meters}"
    )
    cli::cli_progress_done(id = step_id)
    return(vec * 0.3048)
  }
}

#' Standardize Secchi Depth Parameters to Centimeters
#'
#' Validates and scales Secchi disk water clarity records to centimeters.
#' Automatically skips operations if values are already declared in centimeters.
#'
#' @param vec A numeric vector of Secchi measurements.
#' @param secchi_unit Character string representing the units of the `Secchi` parameter. Supported
#'   options: "centimeters", "meters".
#' @param config_path Character string path to the survey's YAML configuration file used for
#'   contextual error reporting.
#' @return A numeric vector representing Secchi Depth scaled to centimeters.
#' @noRd
convert_secchi <- function(vec, secchi_unit, config_path) {
  # Set up progress message
  status <- new.env()
  status$msg <- ""
  step_id <- cli::cli_progress_step(
    msg = "Standardizing units of {.var Secchi} column",
    msg_done = "Standardizing units of {.var Secchi} column{status$msg}"
  )

  # Define valid units for secchi_unit
  valid_units <- c("centimeters", "meters")

  # Exit with error if col_units isn't specified
  if (is.null(secchi_unit) || secchi_unit == "") {
    cli::cli_abort(c(
      "x" = "No {.field col_units} provided for {.var Secchi}",
      "!" = "Please specify a valid {.field col_units} in {.path {config_path}}",
      "i" = "Supported units are: {.val {valid_units}}"
    ))
  }

  # Check for standardized secchi_unit and provide error if no match
  if (!secchi_unit %in% valid_units) {
    cli::cli_abort(c(
      "x" = "Invalid {.field col_units} {.val {secchi_unit}} for {.var Secchi}",
      "!" = "Please specify a valid {.field col_units} in {.path {config_path}}",
      "i" = "Supported units are: {.val {valid_units}}"
    ))
  }

  # Skip if secchi_unit is centimeters
  if (secchi_unit == "centimeters") {
    status$msg <- cli::format_inline(
      "... already in {.val centimeters}. No conversion necessary."
    )
    cli::cli_progress_done(id = step_id)
    return(vec)
    # Otherwise, if secchi_unit is meters, convert to centimeters
  } else if (secchi_unit == "meters") {
    status$msg <- cli::format_inline(
      "... converted from {.val meters} to {.val centimeters}"
    )
    cli::cli_progress_done(id = step_id)
    return(vec * 100)
  }
}

# Standardize CDFW tide codes
standardize_tide_code <- function(df_data) {
  # Check if df_data is a non-empty data.frame
  check_output_df(df_data)

  df_data |>
    dplyr::mutate(
      Tide = dplyr::case_match(
        .data$Tide,
        1 ~ "High Slack",
        2 ~ "Ebb",
        3 ~ "Low Slack",
        4 ~ "Flood"
      )
    )
}
