# Pipeline preflight function and helpers

#' Extract Data Source Inventory from Configuration
#'
#' Parses the input configurations from a pipeline YAML definition to build a distinct list
#' of all unique data sources (such as EDI repositories or local files) slated for ingestion.
#'
#' @param cfg_inputs A list representing a parsed `inputs` block from the YAML configuration file.
#' @return A tibble with two character columns:
#'   * `type`: The source type categorization.
#'   * `detail`: The unique tracking identifier or path matching that source type.
#' @noRd
extract_source_inventory <- function(cfg_inputs) {
  purrr::map(cfg_inputs, function(input) {
    type <- purrr::pluck(input, "input_type", .default = "unknown")

    detail <- switch(
      type,
      "API-EDI" = purrr::pluck(
        input,
        "input_package_id",
        .default = "UNKNOWN"
      ),
      "local_file" = purrr::pluck(
        input,
        "input_path",
        .default = "unspecified path"
      ),
      "unknown"
    )

    tibble::tibble(type = type, detail = detail)
  }) |>
    purrr::list_rbind() |>
    dplyr::distinct(.data$type, .data$detail)
}

#' Extract Timezone Configuration across Pipeline Inputs
#'
#' Iterates through all pipeline input configuration entries, plucks their declared baseline
#' timezones, and returns a structured mapping. Missing entries are skipped automatically.
#'
#' @param cfg_inputs A list representing a parsed `inputs` block from the YAML configuration file.
#' @return A tidy tibble containing two character columns:
#'   * `input_id`: The unique tracking string identifier for the source input.
#'   * `timezone`: The target Olson timezone string mapping.
#' @noRd
extract_timezone_settings <- function(cfg_inputs) {
  purrr::map(cfg_inputs, function(input) {
    tz <- purrr::pluck(input, "timezone", .default = NA_character_)
    tibble::tibble(input_id = input$input_id, timezone = tz)
  }) |>
    purrr::list_rbind() |>
    tidyr::drop_na("timezone")
}

#' Extract Column Unit Configurations across Pipeline Inputs
#'
#' Extracts and flattens column-level unit metadata settings across all registered inputs.
#' It traverses the deeper schema structures to pull target variables and unit fields into a
#' single comprehensive overview table.
#'
#' @param cfg_inputs A list representing a parsed `inputs` block from the YAML configuration file.
#' @return A tidy tibble containing three character columns:
#'   * `input_id`: The tracking string identifier for the parent source input.
#'   * `var`: The target case-standardized column name destination.
#'   * `unit`: The expected units string specification.
#' @noRd
extract_unit_settings <- function(cfg_inputs) {
  purrr::map(cfg_inputs, function(input) {
    if (!"columns" %in% names(input)) {
      return(NULL)
    }

    purrr::map(input$columns, function(col) {
      if ("col_units" %in% names(col)) {
        tibble::tibble(
          input_id = input$input_id,
          var = col$target_name,
          unit = col$col_units
        )
      }
    })
  }) |>
    purrr::flatten() |>
    purrr::compact() |>
    purrr::list_rbind()
}

#' Render Source Inventory Report to Console
#'
#' Formats and prints a clean bulleted inventory log of all active data tracking repositories
#' mapped in the configuration profile using `cli` semantic alerts.
#'
#' @param inventory A tibble generated by `extract_source_inventory()` outlining the `type`
#'   and `detail` fields for active inputs.
#' @return Returns `NULL` invisibly; outputs formatted lines to the console interface as a
#'   side effect.
#' @noRd
render_source_inventory <- function(inventory) {
  if (nrow(inventory) == 0) {
    return(invisible(NULL))
  }

  cli::cli_alert_info("Active Pipeline Data Source Inventory:")
  ul_source <- cli::cli_ul()

  purrr::pwalk(inventory, function(type, detail) {
    if (type == "API-EDI") {
      cli::cli_li("EDI Repository (edi.{detail})")
    } else if (type == "local_file") {
      cli::cli_li("Local File ({.path {detail}})")
    } else {
      cli::cli_li("External Target System (Type: {type})")
    }
  })

  cli::cli_end(id = ul_source)
  invisible(NULL)
}

#' Render Preflight Timezone Report
#'
#' Evaluates the homogeneity of timezones declared across inputs. It reports a single streamlined
#' confirmation if a uniform rule applies, prints a high-visibility breakdown if heterogeneous
#' settings are discovered, or logs an explicit warning if no timezones are declared.
#'
#' @param tz_settings A tibble of timezone records built by `extract_timezone_settings()`.
#' @return Returns `NULL` invisibly; outputs list summaries to the console interface as a
#'   side effect.
#' @noRd
render_preflight_timezones <- function(tz_settings) {
  unique_tzs <- unique(tz_settings$timezone)

  if (length(unique_tzs) == 1) {
    cli::cli_li(
      "Timezone Setting: {.emph {unique_tzs}} (Will align to {.val America/Los_Angeles})"
    )
  } else if (length(unique_tzs) > 1) {
    cli::cli_li("Timezone Setting: {.strong More than one found}:")
    ul_tz <- cli::cli_ul()
    purrr::pwalk(tz_settings, function(input_id, timezone) {
      cli::cli_li("{.var {input_id}} is set to {.emph {timezone}}")
    })
    cli::cli_li("These will align to {.val America/Los_Angeles}")
    cli::cli_end(id = ul_tz)
  } else {
    cli::cli_li(
      "Timezone Setting: {.strong NOT DEFINED - This will result in an error if not specified}"
    )
  }

  invisible(NULL)
}

#' Render Preflight Variable Units Report
#'
#' Loops across standard variable unit settings. If a variable is configured with conflicting
#' source units across distinct inputs, this function identifies the mismatch and logs a
#' prominent warning list detailing the conflicting settings.
#'
#' @param unit_settings A tibble of column-level unit records built by `extract_unit_settings()`.
#' @return Returns `NULL` invisibly; outputs structured messages to the console interface as a
#'   side effect.
#' @noRd
render_preflight_units <- function(unit_settings) {
  if (nrow(unit_settings) == 0) {
    return(invisible(NULL))
  }

  # Determine if any variable maps to more than one unique unit
  multi_vars <- unit_settings |>
    dplyr::distinct(.data$var, .data$unit) |>
    dplyr::count(.data$var) |>
    dplyr::filter(.data$n > 1) |>
    dplyr::pull(.data$var)

  single_units <- unit_settings |>
    dplyr::filter(!.data$var %in% multi_vars) |>
    dplyr::select("var", "unit") |>
    dplyr::distinct()

  multi_units <- unit_settings |> dplyr::filter(.data$var %in% multi_vars)

  # Print standard uniform units
  if (nrow(single_units) > 0) {
    purrr::pwalk(single_units, function(var, unit) {
      cli::cli_li(
        "Parameter Unit Setting: {.var {var}} expects {.emph {unit}}"
      )
    })
  }

  # Print high-visibility messaging for variable with more than one unique unit
  if (nrow(multi_units) > 0) {
    purrr::walk(unique(multi_units$var), function(var) {
      cli::cli_li(
        "Parameter Unit Setting: {.strong More than one found} for {.var {var}}:"
      )
      ul_unit <- cli::cli_ul()
      multi_units |>
        dplyr::filter(.data$var == var) |>
        dplyr::select("input_id", "unit") |>
        purrr::pwalk(function(input_id, unit) {
          cli::cli_li("{.var {input_id}} expects {.emph {unit}}")
        })
      cli::cli_end(id = ul_unit)
    })
  }

  invisible(NULL)
}

#' Display Pre-Flight Metadata Dashboard for a Pipeline
#'
#' Acts as the entry gatekeeper dashboard for the survey pipeline execution flow. This function
#' reads the configuration YAML, logs high-impact console banners detailing survey settings,
#' validates the basic structure of the configuration YAML, and audits unit or timezone conformance
#' blocks prior to initiating any download processes.
#'
#' @param config_path Character string path to the survey's YAML configuration file.
#' @return The parsed configuration `list` object invisibly, allowing for streamlined functional
#'   pipe chaining.
#' @noRd
run_pipeline_preflight <- function(config_path) {
  # Import configuration file for survey
  config <- yaml::read_yaml(config_path)

  # Extract metadata pieces safely
  survey_name <- purrr::pluck(
    config,
    "source_metadata",
    "name",
    .default = "Unknown survey"
  )
  acronym <- purrr::pluck(
    config,
    "source_metadata",
    "acronym",
    .default = "UNK"
  )
  last_update <- purrr::pluck(
    config,
    "update_status",
    "last_update",
    .default = "Never"
  )

  # Console Announcement Block
  cli::cli_div(
    theme = list(span.emph = list(color = "orange", font_weight = "bold"))
  )

  # Bundle all text lines together to keep them inside the border walls
  raw_content <- c(
    paste0("PRE-RUN CHECK: ", acronym),
    "", # Adds an empty blank row spacer
    "Pipeline Initiated",
    paste0("Survey: ", survey_name),
    "", # Adds an empty blank row spacer
    "Historical Metadata Tracking Reference"
  )

  # Force a minimum width (e.g., 85 characters) so the box looks wider and more balanced,
  # but allow it to grow larger if a massive survey scope name overflows 85 characters.
  content_width <- 85
  box_width <- content_width + 2
  box_content <- stringr::str_pad(
    raw_content,
    width = content_width,
    side = "right"
  )

  # Render the unified box frame layout
  banner <- cli::boxx(
    box_content,
    padding = 0,
    align = "left",
    width = box_width
  )
  cat(banner, "\n")

  # Print date of last update
  cli::cli_alert_info(
    "This survey dataset was last successfully updated on: {.val {last_update}}"
  )

  # Display all data sources
  source_inventory <- extract_source_inventory(config$inputs)
  render_source_inventory(source_inventory)
  cli::cli_text("")

  # Run EDI status check if EDI is a data source
  if ("edi_package" %in% names(config$update_status)) {
    cli::cli_alert_info("Running EDI Status Check")
    cli::cli_text("")
    ls_edi_info <- check_edi_status(config$update_status, config_path)

    # Provide link to EDI data package metadata for current revision
    edi_base_url <- "https://portal.edirepository.org/nis/metadataviewer?packageid=edi"
    edi_url <- purrr::map_chr(
      ls_edi_info,
      \(x) paste(edi_base_url, x$edi_pkg_id, x$curr_rev, sep = ".")
    )

    cli::cli_alert_info(
      "{cli::qty(length(edi_url))}Link{?s} to EDI data package metadata for current revision{?s}:"
    )
    purrr::walk(edi_url, \(url) cli::cli_bullets(c("*" = "{.url {url}}")))
    cli::cli_text("")
  }

  # Run structural integrity audit across all inputs first
  step_str <- cli::cli_progress_step(
    "Checking configuration structural schema integrity"
  )
  purrr::walk(config$inputs, function(input) {
    check_config_structure(input, config_path)
  })
  cli::cli_progress_done(id = step_str)
  cli::cli_text("")

  # Additional Critical Reminders
  cli::cli_bullets(c(
    "!" = "CRITICAL REMINDER: Has the provider altered column metadata or added parameters for this revision?",
    "!" = "Please verify that the settings in the YAML configuration file match current metadata specifications for the dataset.",
    "i" = "The current metadata settings in the configuration file include:"
  ))
  ul_settings <- cli::cli_ul()

  # Metadata compliance reporting - timezones and units
  tz_settings <- extract_timezone_settings(config$inputs)
  unit_settings <- extract_unit_settings(config$inputs)

  # Render mappings
  render_preflight_timezones(tz_settings)
  render_preflight_units(unit_settings)

  # Close custom theme blocks and exit out cleanly
  cli::cli_end(id = ul_settings)
  cli::cli_text("")
  cli::cli_text(cli::col_cyan(
    "If these specifications are incorrect, modify the YAML configuration file: {.path {config_path}}"
  ))
  cli::cli_rule()

  invisible(config)
}
