# Data caching functions

#' Generate Cryptographic Cache Identifiers for Raw and Standardized Pipelines
#'
#' Generates unique, reproducible MD5 hashes based on the configuration files to determine
#' caching states. The `RAW` identifier hashes connection metadata (`update_status` and
#' `input_` paths) to track changes in data sourcing, while the `STD` identifier hashes the
#' complete configuration parameters to catch changes in column standardizations, timezones,
#' or parameters. If applicable, active EDI revision strings are appended to prevent working
#' with outdated remote versions.
#'
#' @param config The full parsed list from the YAML configuration file.
#' @param edi_info A nested list structure returned from `check_edi_status()` outlining active
#'   package revision states, or `NULL` if not processing an EDI pipeline source.
#'
#' @return A named list of length two elements containing the generated character string hashes:
#'   * `raw`: The data sourcing signature cache identifier.
#'   * `std`: The full structural schema specification cache identifier.
#' @noRd
create_cache_ids <- function(config, edi_info) {
  # Extract data import keys from configuration file for the "raw" hash
  config_def_raw <- list(
    config$update_status,
    purrr::map(
      config$inputs,
      \(x) purrr::keep_at(x, \(y) stringr::str_detect(y, "^input_"))
    )
  )
  # Use the entire configuration file for the "std" hash
  config_def_std <- config

  # Generate unique md5 hashes for each. Extract the first 10 characters of the MD5
  # hash for conciseness
  config_hash_raw <- substr(digest::digest(config_def_raw, algo = "md5"), 1, 10)
  config_hash_std <- substr(digest::digest(config_def_std, algo = "md5"), 1, 10)

  # Create cache ID's
  acronym <- config$source_metadata$acronym
  if (!is.null(edi_info)) {
    # If EDI is a data source, extract info from EDI status check to be added to cache IDs
    # to make sure cached data is still from the current package revision
    edi_id <- purrr::map_chr(
      edi_info,
      \(x) paste("edi", x$edi_pkg_id, x$curr_rev, sep = "_")
    )

    # Combine edi_id if more than one package ID is provided
    edi_id <- if (length(edi_id) > 1) paste(edi_id, collapse = "_") else edi_id

    raw <- paste(acronym, edi_id, "RAW", config_hash_raw, sep = "_")
    std <- paste(acronym, edi_id, "STD", config_hash_std, sep = "_")
  } else {
    raw <- paste0(acronym, "_RAW_", config_hash_raw)
    std <- paste0(acronym, "_STD_", config_hash_std)
  }

  tibble::lst(raw, std)
}

#' Stateful Execution Wrapper with Automated Cache Management and Expiration
#'
#' Evaluates an expression securely behind a file-cached boundary layer in `data-raw/.cache/`.
#' The wrapper checks for an existing RDS cache artifact matching the unique hash pattern.
#' It automatically handles manual cache drops (`force_refresh = TRUE`) and tracks file age records
#' via `file.mtime()` to invalidate and purge local records that exceed the defined maximum age
#' threshold.
#'
#' @param cache_id Character string hash identifier generated by `create_cache_ids()`.
#' @param expr An unquoted R expression or code block to evaluate if no valid cache file matches.
#' @param force_refresh Logical flag indicating whether to bypass existing local `.rds` cache
#'   assets and force fresh API transactions and re-processing. Defaults to `FALSE`.
#' @param max_age_days Numeric ceiling indicating the maximum lifespan (in days) of local cached
#'   objects before expiration triggers an automatic update. Defaults to 7.
#'
#' @return The evaluated result of `expr`, either pulled from an existing local `.rds` cache
#'   artifact or captured from active evaluation.
#' @noRd
run_with_cache <- function(
  cache_id,
  expr,
  force_refresh = FALSE,
  max_age_days = 7
) {
  # Define and create cache_dir if it doesn't exist already
  cache_dir <- "data-raw/.cache"
  if (!dir.exists(cache_dir)) {
    dir.create(cache_dir, recursive = TRUE)
  }

  # Search for existing cache by hash pattern
  # Looks for any file ending with "_[your_hash].rds" in the directory
  existing_files <- list.files(
    cache_dir,
    pattern = paste0(cache_id, "_\\d{4}-\\d{2}-\\d{2}\\.rds$"),
    full.names = TRUE
  )

  # Target the matched file if it exists
  cache_path <- if (length(existing_files) > 0) existing_files[1] else NULL

  # Manually force refresh if force_refresh is TRUE
  if (force_refresh && !is.null(cache_path) && file.exists(cache_path)) {
    cli::cli_alert_warning(
      "Force refresh active. Purging old cache file: {.file {basename(cache_path)}}"
    )
    unlink(cache_path)
    cache_path <- NULL
  }

  # Automatic expiration check
  if (!is.null(cache_path) && file.exists(cache_path)) {
    # Get the last modification time of the file
    cache_time <- file.mtime(cache_path)
    # Calculate difference in days relative to current time
    cache_age <- as.numeric(difftime(Sys.time(), cache_time, units = "days"))

    if (cache_age > max_age_days) {
      cli::cli_bullets(c(
        "!" = "Cache expired: Local cache {.file {basename(cache_path)}} is {.val {round(cache_age, 1)}} days old.",
        "i" = "Purging file and requesting fresh data..."
      ))
      unlink(cache_path)
      cache_path <- NULL
    }
  }

  # Define if cache is for raw or standardized data to taylor messaging
  cache_type <- if (stringr::str_detect(cache_id, "^\\w+_RAW_")) {
    "raw"
  } else {
    "std"
  }

  # Load cached data if the file survived the force and expiration filters
  if (!is.null(cache_path) && file.exists(cache_path)) {
    # Taylor messaging based on cached data type
    if (cache_type == "raw") {
      cli::cli_bullets(c(
        "v" = "Using cached raw data: {.path {cache_path}}",
        "i" = "Skipping API downloads and file imports"
      ))
    } else if (cache_type == "std") {
      cli::cli_bullets(c(
        "v" = "Using cached standardized data: {.path {cache_path}}",
        "i" = "Skipping data imports and standardization"
      ))
    }
    return(readRDS(cache_path))
  }

  # Run expr if there isn't cached data at cache_path
  # Taylor messaging based on cached data type
  if (cache_type == "raw") {
    cli::cli_alert_info(
      "No valid raw data cache found. Commencing active data downloads..."
    )
  } else if (cache_type == "std") {
    cli::cli_alert_info(
      "No valid standardized data cache found. Looking for raw data cache..."
    )
  }
  result <- force(expr)

  # Generate timestamped cache path and save
  current_date <- Sys.Date()
  new_cache_path <- file.path(
    cache_dir,
    paste0(cache_id, "_", current_date, ".rds")
  )

  saveRDS(result, new_cache_path)
  # Taylor messaging based on cached data type
  if (cache_type == "raw") {
    cli::cli_alert_success(
      "Raw data successfully cached to {.path {new_cache_path}}"
    )
  } else if (cache_type == "std") {
    cli::cli_alert_success(
      "Standardized data successfully cached to {.path {new_cache_path}}"
    )
  }

  return(result)
}
